apiVersion: stack.zncdata.net/v1alpha1
kind: Airbyte
metadata:
  labels:
    app.kubernetes.io/name: airbyte
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/part-of: airbyte-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: airbyte-operator
  name: airbyte
spec:
  clusterConfig:
    serviceAccountName: airbyte-admin
    stateStorage:
      s3:
        bucket:
          reference: "airbyte-state-storage"
        pathStyle_access: true
    logs:
      s3:
        bucket:
          reference: "airbyte-dev-logs"
        pathStyle_access: true
    config:
      database:
        reference: database-sample
  server:
    enabled: true
    roleConfig:
      replicas: 1
      image:
        repository: airbyte/server
        tag: 0.50.30
        pullPolicy: IfNotPresent
      service:
        port: 8001
        type: ClusterIP
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
  worker:
    enabled: true
    #    debug: true
    roleConfig:
      image:
        repository: airbyte/worker
        tag: 0.50.30
        pullPolicy: IfNotPresent
      replicas: 1
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
  airbyteApiServer:
    enabled: false
    roleConfig:
      image:
        repository: airbyte/airbyte-api-server
        tag: 0.50.30
        pullPolicy: IfNotPresent
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
      replicas: 1
      service:
        port: 80
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

  airbyteBootloader:
    enabled: true
    roleConfig:
      image:
        repository: airbyte/airbyte-bootloader
        tag: 0.50.30
        pullPolicy: IfNotPresent
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  connectorBuilderServer:
    enabled: true
    roleConfig:
      image:
        repository: airbyte/connector-builder-server
        tag: 0.50.30
        pullPolicy: IfNotPresent
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
      replicas: 1
      service:
        port: 80
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  keycloak:
    enabled: false
    roleConfig:
      replicas: 1
      image:
        repository: airbyte/keycloak
        tag: 0.50.30
        pullPolicy: IfNotPresent
      service:
        port: 80
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  temporal:
    enabled: false
    roleConfig:
      replicas: 1
      image:
        repository: temporalio/auto-setup
        tag: 1.20.1
        pullPolicy: IfNotPresent
      service:
        port: 7233
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  webApp:
    enabled: true
    roleConfig:
      replicas: 1
      image:
        repository: airbyte/webapp
        tag: 0.50.30
        pullPolicy: IfNotPresent
      service:
        port: 80
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
      ingress:
        enabled: true
        host: www.zncdata.net
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  cron:
    enabled: true
    roleConfig:
      replicas: 1
      image:
        repository: airbyte/cron
        tag: 0.50.30
        pullPolicy: IfNotPresent
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
  podSweeper:
    enabled: true
    roleConfig:
      replicas: 1
      image:
        repository: bitnami/kubectl
        tag: latest
        pullPolicy: IfNotPresent
      config:
        resources:
          cpu:
            max: 150m
            min: 100m
          memory:
            limit: 512Mi
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: default
      foo:
        replicas: 1
        config:
          resources:
            cpu:
              max: 150m
              min: 100m
            memory:
              limit: 512Mi
        matchLabels:
          app: foo
